### PR TITLE
Find link elements anywhere in the document.

### PR DESCRIPTION
**Pull request by kevincox**
https://github.com/Reeywhaar/want-my-rss/issues/41

This still doesn't find dynamically added links but that is probably not worth the performance costs whereas this is basically free.

Also move the attribute checking into CSS to improve performance.

Fixes https://github.com/Reeywhaar/want-my-rss/issues/41

### CODE REVIEW

**Comment by kevincox** [comment]
Ping @Reeywhaar is there anything I can do to help move this forward? I would like to have YouTube feeds working (at least after a reload).

**Comment by Reeywhaar** [comment]
I'll take a look in next 24 hours :-)

**Comment by Reeywhaar** [comment]
So, it seems new version got approved :-)

**Comment by kevincox** [comment]
Thanks!

**Pull request merged**
